# Generated by Django 5.1.5 on 2025-04-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("publisher", models.CharField(max_length=200)),
            ],
        ),
    ]
